# Generated by Django 6.0.3 on 2026-03-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantuty',
            new_name='quantity',
        ),
    ]
